# Generated by Django 5.2.8 on 2025-11-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0002_blooddonor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
