# Generated by Django 5.2.8 on 2025-11-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0004_bloodrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='units_approved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='reason',
            field=models.TextField(),
        ),
    ]
