# Generated by Django 5.2.8 on 2025-11-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('emergency', 'Emergency Services'), ('consultation', 'Consultation'), ('diagnostics', 'Diagnostics & Imaging'), ('laboratory', 'Laboratory'), ('specialized', 'Specialized Care'), ('other', 'Other Services')], default='other', max_length=20),
        ),
    ]
