# Generated by Django 5.2.8 on 2025-11-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
